### ISSUE TITLE
Please stop hitting mpv.srsfckn.biz every few seconds on every machine with your dumb updater kthxbye

### ISSUE THREAD

**Issue by lachs0r** [RosadinTV/rosadintv.github.io#1]

**Comment by RosadinTV** [comment]
Like the name says, 'the dumb updater' at the program startup (yes, only at startup, not 'every few seconds on every machine') finds at mpv.srsfckn.biz if a new MPV version is available for download.
I do not understand why this angers you.
*PS: If the user wants, you can disable automatic updates in the options menu

**Comment by lachs0r** [comment]
Try to limit the update rate per install. Once in 24 hours is totally reasonable.

Also, you should really do something about your updater’s security. Do not use plain HTTP, use (and verify!) certificates. Do not assume people will not hijack it to distribute malware; this happens all the time with broken updaters.

**Comment by RosadinTV** [comment]
Yes, check updates once 24 hours is OK, in a future update maybe change this.
And with Updater Security I dont care about this, at least at the moment ..  i mean .. it is unlikely that MPV, YouTube-DL or Livestreamer site gonna be hacked or changed.
One thing that i can do is do not allow users to use old updaters in case that weird things like this happens.
This Project is a personal hobbie that i wanted to share, but i work alone and im not a professional, so that kinds of bugs is common, with the passage of time I try to improve.

**Comment by lachs0r** [comment]
You don’t seem to understand where I’m going with this. You are essentially distributing malware here and I ask you to stop until you have fixed these fundamental flaws. Doing it just by yourself as a hobby is not an excuse for this kind of irresponsible programming. Most open-source projects are just a hobby. Implementing a more secure updater is not that hard.

It may seem unlikely that my server (which hosts mpv builds), youtube-dl’s server or livestreamer’s site is hijacked, and it may seem unlikely that YOUR site (which instructs the updater what to download) gets hijacked, but that changes when there’s a piece of software conveniently installed on people’s computers that doesn’t even bother to verify what is downloaded and executed. That makes all these sites viable attack targets. Not to mention MitM, since you’re not even using HTTPS.

I didn’t buy a codesign certificate for shits and giggles. I did this to make it at least somewhat less viable for people with a questionable sense of morality to hijack my downloads. There’s no such thing as “unlikely” when it comes to security. “Unlikely” is the most harmful assumption you could possibly make.

**Comment by RosadinTV** [comment]
Think we have two different views about hobbies, but really understand your concerns .. personally i dont care a lot about this things.
But you are right, as the Project is public, i need to try to enhace the updater security or at least put a warning.
PS: I have checked Livestreamer, YouTube-DL and MPV and all of this support HTTPS so your idea is fully viable.

**Comment by lachs0r** [comment]
Remember to use HTTPS for your own site as well. For simplicity, you can just check the hashes of the downloaded files (use something cryptographically secure, i.e. not CRC). I assume you write the update instruction file manually, so you can verify the digital signatures yourself before changing that.

Until you have implemented a minimum of security, I recommend removing the updater. Nobody reads warnings.

**Comment by RosadinTV** [comment]
Partially done.
Now, all updates (include 3rd party) are via HTTPS.

**Comment by RosadinTV** [comment]
Fully done.
Now, the program search for updates once a day by default (the user can change this to once a week or never)
