### ISSUE TITLE
ayuda para reproducir canal

### ISSUE THREAD

**Issue by manolouy** [RosadinTV/rosadintv.github.io#10]
Buenas! Queria saber si alguien puede ayudarme a reproducir esta emision en Rosadin http://www.canal10.com.uy/pages/live-tv

Si sirve de algo, mediante este codigo en un archivo xml, es posible reproducirla en un conocido media center.
[xml.txt](https://github.com/RosadinTV/rosadintv.github.io/files/264236/xml.txt)

`<item>
<title>Canal 10</title>
<link>$doregex[url]</link>
<regex>
<name>url</name>
<expres>hls": "(.*?)"</expres>
<page>http://content.zetatv.com.uy/content/1a92dbdb-5701-46cc-b865-f2b17195afbb/embed/url/?video_type=wowzaadmin&amp;token=</page>
<referer>http://content.zetatv.com.uy/content/1a92dbdb-5701-46cc-b865-f2b17195afbb/embed/?poster=http://web10.images.production.s3.amazonaws.com/uploads/image/image/398/AHORA_EN_VIVO-950x540.jpg</referer>
<x-req>XMLHttpRequest</x-req>
<cookieJar>$doregex[Cookie]</cookieJar>
</regex>
<regex>
<name>Cookie</name>
<expres></expres>
<page>http://content.zetatv.com.uy/content/1a92dbdb-5701-46cc-b865-f2b17195afbb/embed/?poster=http://web10.images.production.s3.amazonaws.com/uploads/image/image/398/AHORA_EN_VIVO-950x540.jpg</page>
<referer>http://www.canal10.com.uy/pages/live-tv</referer>
<cookieJar></cookieJar>
</regex>
<thumbnail>http://web10.images.production.s3.amazonaws.com/uploads/image/image/66/logo-canal10.jpg</thumbnail>
</item>
`

**Comment by RosadinTV** [comment]
Hola, el programa no es compatible actualmente con XML por lo que ese tipo de enlaces con Regex es solo posible hacerlos funcionar mediante la creación de Plugins.
Por lo general no doy soporte para canales en particular pero este era fácil y legal así que te dejo el Plugin ya compilado mas el código fuente por si te sirve de guía en un futuro.
https://mega.nz/#!T0YBnbqB!Mza3AcDnD3ql2op1TNZKyw6IJgnHofT_p31JRvd92d4
Solo tenes que descomprimirlo y moves el archivo 'RTV_PLUGIN_CANAL10URUGUAY.exe' a la carpeta Plugins ubicada donde tenes el programa, luego dentro del programa abris la categoría Plugins y listo :)

**Comment by manolouy** [comment]
Muchisimas gracias por el plugin!
Estuve mirando los archivos del código fuente y hasta ahí no llego jeje

**Comment by RosadinTV** [comment]
Entiendo, no hay problema, lo importante es que el Plugin ya compilado te sirva :)
