### ISSUE TITLE
lista remota

### ISSUE THREAD

**Issue by manolouy** [RosadinTV/rosadintv.github.io#12]
Buenas!
Hay alguna manera de tener una lista remota de forma permanente sin tener que ir a Abrir fuente / Lista remota y ahí pegar el enlace para cargar la lista?
Gracias y saludos!

**Comment by acce1804** [comment]
Si  se puede: Una vez abierta la lista remota si te fijas en el lado superior derecho de la pantalla hay una flecha, guardala en favoritos y listo.

**Comment by manolouy** [comment]
No me había dado cuenta, gracias!

**Comment by RosadinTV** [comment]
Ya lo contesto @acce1804 , recuerda que además puedes anclarlo a la navegación (barra izquierda) desde ese mismo menú.
