### ISSUE TITLE
Problema con enlaces rtsp

### ISSUE THREAD

**Issue by gladysromildena** [RosadinTV/rosadintv.github.io#16]
Los enlaces que comienzan con rtsp se reproducen durante 1 minuto y 30 segundos y luego se detiene por completo la reproduccion.
Ejemplos:
Canal 13
rtsp://stream.eltrecetv.com.ar/live13/13tv/13tv1

Magazine
rtsp://stream.mgzn.tv/live/mgzntv/mgzntv

Canal 26
rtsp://live-edge01.telecentro.net.ar:80/live/26hd-360

TN
rtsp://stream.tn.com.ar/live/tnhd1

En versiones anteriores funcionaban correctamente. (ej. version 112)
Gracias por el soporte. Muy buen programa.

**Comment by RosadinTV** [comment]
No cambie nada en relación a RTSP pero es muy cierto que funciona mal, veré si puedo conseguir algún dumper especifico (como youtube-dl/livestreamer) pero para este este protocolo o por lo menos mejorarlo un poco.

**Comment by gladysromildena** [comment]
Muy agradecida. Que tenga un buen dia.

**Comment by RosadinTV** [comment]
Con el ultimo update optimize un poco el protocolo.
Si un futuro encuentro un dumper lo agregare.
Saludos

**Comment by gladysromildena** [comment]
Le agradezco mucho. Ahora ya no se queda tildado al minuto y medio. Quedo muy bien. Tenga un buen dia. Saludos.

**Comment by manolouy** [comment]
El problema de la detención al minuto 1:30 se soluciono.
En mi caso, ahora creo que tengo problemas de buffer con este tipo de enlace.
Dejo un par de videos testeando un enlace con Rosadin 124 mostrando mi problema y otro con Rosadin 108 funcionando bien.

rtv 108
https://www.youtube.com/watch?v=iLUoDjJMqOo

rtv 124
https://www.youtube.com/watch?v=2bCnQgVa_3U

**Comment by RosadinTV** [comment]
Efectivamente tenes razón.
Para el próximo update lo intento mejorar de nuevo, además de una nueva opcion de mostrar los ítems en forma cuadriculada.
Sera algo similar a esto: http://s33.postimg.org/cv5f6wma7/rtv_testing2.jpg

**Comment by manolouy** [comment]
Los enlaces rtsp ahora funcionan perfecto en manejo de caché original y estricto. Gracias ;D
La vista en cuadriculas se ve bien y esos pugins en la barra lateral tambien :P dan ganas de probarlos jeje

**Comment by RosadinTV** [comment]
Que bien 😄 
Todavía no esta listo de lo de la vista en cuadriculas pero esta en desarrollo.
En cuanto a los Plugins que figuran a la izquierda son personales, no creo que los publique.
