### ISSUE TITLE
reproduccion desde google drive

### ISSUE THREAD

**Issue by manolouy** [RosadinTV/rosadintv.github.io#17]
Buenas! Que tal?
Tengo problemas para reproducir "videos largos" desde google drive. Supongamos un video de 1:50hs faltando 10 o 15 minutos para que finalice, cuando se gastan los +segundos y + mb que hay en cache, la reproducción se detiene y no termina de descargar los minutos restantes. Esto me sucedió las 3 veces que intente visualizar archivos dese google drive. Dos de los archivos eran de 700mb y el restante de 2gb, por lo que parece ser un problema de duración y no de el peso de los archivos.

**Comment by RosadinTV** [comment]
Me suena a que se debe a un problema de MPV (el reproductor) o YouTube-DL pero es difícil que pueda reproducir el problema.
En un futuro cercano tengo pensado cambiar el modo en que se maneja YouTube-DL con los reproductores, quizás eso solucione el problema :P

**Comment by manolouy** [comment]
Si queres intentar reproducir el problema te puedo pasar algún link.
Aclaro que esto me sucedió reproduciendo los videos sin pausar, retroceder ni adelantar la reproducción, es decir, lanzar el video sin tocar nada mas.

**Comment by RosadinTV** [comment]
Si, por eso decía, demanda mucho tiempo reproducir el problema porque debo dejar un video de mas de 1 hora reproduciéndose.
En el ultimo update que acabo de lanzar quizás se haya resuelto el problema.

**Comment by manolouy** [comment]
Genial. La proxima vez que mire un video desde GD te comento a ver que tal.
Por lo pronto hice un test rápido con un video de 700mb. Cacheó hasta 512mb, adelanté el video hasta la mitad y termino de cachear el resto. Se ve prometedor :D
Gracias y saludos!

**Comment by manolouy** [comment]
Volvi a intentar anoche y el problema continua. La reproduccion se detuvo aun teniendo +300 MB en caché.

**Comment by RosadinTV** [comment]
Proba cambiando la opción Manejo de cache (MPV) a Estricto, porque ayer debido a que algunos usuarios tenían problemas volvi a ponerlo como antes por defecto (Original)

**Comment by manolouy** [comment]
Si, ese intento que te comente fue con la actualización intermedia, cuando rosadin estaba solo con manejo de cache estricto.

**Comment by RosadinTV** [comment]
Entonces ya no se me ocurre nada mas 😵 
Como ultima cosa pudieras probar poniendo la opción Manejo de cache (MPV) a Estricto y la opción Limite de RAM (Livestreamer) a Personalizado e introduci 100
Aunque dudo que eso funcione, debe ser mas bien un bug de MPV, de todas formas lo tendre en mente por si se me ocurre alguna otra solución.

**Comment by manolouy** [comment]
Voy a intentar eso ultimo que me comentas y despues voy a intentar solo con MPV sin pasar por rosadin a ver que pasa.

**Comment by RosadinTV** [comment]
Tenes razón, muy buena idea.
Si te funciona bien sin Rosadin confirmamos que le problema es del programa.

**Comment by RosadinTV** [comment]
Update:
Agregue una opción para Forzar la reconexión de MPV .. asi que tenes otra posibilidad mas para seguir probando 🌵

**Comment by manolouy** [comment]
Descargue la ultima versión de MPV e hice el intento y paso lo mismo. La reproducción se detuvo faltando unos 10 minutos y aún teniendo +60MB en cache, es decir, aparentemente ya estaba la totalidad del video en caché, pero igual se detiene. Así que el problema no es Rosadin :D
Dudo que con el forzado de reconexión funcione, porque como decía, aparentemente el video se descarga completo, pero MPV no quiere reproducir los últimos MB que hay en caché.
De cualquier manera la reconexion forzada se agradece montones, ya que por acá las ips son dinamicas, cambian cada 12 horas y por lo que estuve probando me voy a ahorrar unos cuantos cortes :D por lo menos en los enlaces .ts funciona muy bien.
Gracias por el soporte!

**Comment by RosadinTV** [comment]
Ok, gracias por el reporte :D

**Comment by manolouy** [comment]
Encontré una solución reproduciendo con livestreamer > HTTPSTREAM
Después puse HTTPSTREAM:// al inicio de los links de Google Drive en la lista m3u y funciono perfecto.
