### ISSUE TITLE
Inconveniente con nueva actualizacion

### ISSUE THREAD

**Issue by ricardovieytes** [RosadinTV/rosadintv.github.io#18]
Hola. 
Deseo reportar un inconveniente que ha aparecido luego de la ultima actualizacion.
Los canales se frizan bastante.
Anteriormente, cuando se almacenaba cache asi " 27 s + 0 KB " los canales iban super fluidos, jamas se frizaban, y hasta se podian ver en formato HD con solo 15 megas de coneccion.
Luego de la actualizacion, los canales se frizan, tanto HD como SD. 
Los HD se detienen cada 15 segundos aproximadamente y los SD cada 3 minutos aproximadamente.
Se podra volver a la version anterior? O bien incluir una opcion para que seleccionemos como se almacena cache, segun la velocidad de internet que tengamos?
De antemano, gracias. Salu2.

**Comment by RosadinTV** [comment]
Hola, si, no hay problema.
En la próxima actualización incluyo una opción para cambiar el modo de Cache de MPV. (Original que sería el que estaba antes y estricto que seria el que esta ahora)
Saludos

**Comment by RosadinTV** [comment]
Listo, la opción Original (es decir como estaba en actualizaciones anteriores) ahora es la predeterminada.
Para el que desee tener un manejo mas estricto puede configurarlo desde el menú de opciones.

**Comment by ricardovieytes** [comment]
Muchas gracias. Ya se puede ver los canales fluidos como antes. Salu2.
