### ISSUE TITLE
Mejora

### ISSUE THREAD

**Issue by kiouji** [RosadinTV/rosadintv.github.io#19]
Hola, 

Primero gracias por el programa. Sería bueno poder controlar el programa con las flechas del techado y no solo con el mouse.

**Comment by RosadinTV** [comment]
Si se presiona TAB se puede ir moviendo con la flechas, luego la tecla SPACE equivale a click izquierdo y la tecla MENU a click derecho.

**Comment by kiouji** [comment]
Me funciono, gracias. Ya con esto esta completo.
