### ISSUE TITLE
problema con rosadin cuando se descarga (graba)

### ISSUE THREAD

**Issue by serena13** [RosadinTV/rosadintv.github.io#2]
hola mi estimado, acabo de actualizar rosadin y cuando intento descargar desde algún enlace rosadin se traba y el uso de recursos se dispara, solo sale "cargando livestreamer" y de ahí no pasa,y la pc se me pasma y he tenido que reiniciarla, que crees que sea?en la anterior actualización no pasaba, al reproducir todo anda perfecto, viendo el administrador de tareas veo que livestreamer. exe consume toda la ram y antes no(aunque no creo que el problema sea de livestreamer ya que es exactamente el mismo de la versión anterior).
Este es un enlace con el que lo probé, aunque cabe señalar que tiene el mismo problema con todos los enlaces con que lo he probado 
http://dwstream3-lh.akamaihd.net/i/dwstream3_live@124409/index_3_av-p.m3u8

y aqui te dejo una captura de pantalla con rosadin abierto y el administrador de tareas abierto
http://images.snoork.com/images/9549860993_Captura_de_pantalla_(117).png

P.D. Disculpa por postear el problema en dos lados, no sabia donde ponerlo

**Comment by RosadinTV** [comment]
Listo.
 PD: Para no tener que esperar a que se actualice solo podes ir a: Opciones > Actualizaciones > Buscar actualizaciones
