### ISSUE TITLE
Mejorar diseño

### ISSUE THREAD

**Issue by DerianAndre** [RosadinTV/rosadintv.github.io#2]
Creo que el diseño es bastante malo por los colores y muy simple, la estructura está bien, yo podría ayudar :)

**Comment by RosadinTV** [comment]
Por el momento no pienso cambiar el diseño del programa, además de que en general tuvo buena aceptación por el publico.

**Comment by DerianAndre** [comment]
Por lo menos creo puedes hacer una selección de color base para todo el programa en ves de las 3 opciones actuales (Light, Rojo, Default)

**Comment by RosadinTV** [comment]
Si, esa es buena idea :)

**Comment by DerianAndre** [comment]
Cualquier ayuda con el diseño, ya sea interfaz, logo, o web puedes contactarme sin ningún problema.
Saludos y buen trabajo!

**Comment by RosadinTV** [comment]
Listo :)
