### ISSUE TITLE
Error: Reproductor no encontrado

### ISSUE THREAD

**Issue by GuriGuri2013** [RosadinTV/rosadintv.github.io#5]
Cordial saludo.

Soy nuevo en la aplicación, y este es el mensaje que me arroja cuando intento abrir cualquier canal.  Ya revisé el Firewall, y Livestreamer está hablitado.  

youtube-dl.exe y rtmpdump.exe se encuentran dentro de la carpeta MPV.

Gracias por su tiempo.

**Comment by RosadinTV** [comment]
Hola.
Proba yendo a Opciones > Restaurar  y selecciona Opciones.
Si aun asi no funciona podes probar seleccionado Aplicaciones como restauración.
Y en una ultima instancia pudieras probar ejecutando el programa como administrador.
Saludos

**Comment by RosadinTV** [comment]
Borre mi anterior comentario porque acabo de revisar bajando el programa desde cero y efectivamente hay un problema con la descarga de MPV.
Lo revisare y arreglare ;)

**Comment by RosadinTV** [comment]
Listo, para solucionarlo vuelve a descargar el ejecutable 'RosadinTV.exe' desde la pagina oficial y reemplázalo con el que tienes actualmente.
Luego vas a Opciones > Actualizaciones > Buscar actualizaciones y debería comenzar la descarga de MPV

**Comment by GuriGuri2013** [comment]
Después de seguir sus indicaciones, ahora se queda pegado en "Cargando reproductor", y cuando suspendo la acción, arroja mensaje "Error de reproducción".  Igual sucede cuando doy clic derecho y elijo "Reproducir con MPV". :(

**Comment by RosadinTV** [comment]
Quizas sea un problema del enlace ?
Si me lo pasas lo pruebo y te confirmo.

**Comment by GuriGuri2013** [comment]
Cuando dices "enlace", ¿te refieres a la lista .m3u de canales que intento abrir?  Si es así, ¿cómo te puedo enviar los archivos?

**Comment by RosadinTV** [comment]
Dale click derecho al enlace especifico que no te funciona y luego selecciona 'Copiar enlace al portapapeles' y publica el enlace aquí.

**Comment by GuriGuri2013** [comment]
http://200.76.77.237/LIVE/H01/CANAL415/PROFILE05.m3u8?playkodi=%2F.ts

**Comment by RosadinTV** [comment]
Al menos donde vivo no anda ese enlace, proba abriéndolo desde el navegador y decime si te sale un error o el contenido del enlace (segmentos ts)

**Comment by GuriGuri2013** [comment]
Lo intento abrir desde la barra de direcciones, y la página se queda en blanco.

**Comment by RosadinTV** [comment]
Entonces efectivamente el problema aquí es que ese enlace que intentas abrir no funciona

**Comment by GuriGuri2013** [comment]
¿Me puedes, por favor, enviar alguno que te funcione?

**Comment by RosadinTV** [comment]
No doy soporte para ese tipo de cosas (principalmente por cuestiones legales) pero estoy seguro que si pones un mail de contacto alguien te lo enviara ;)

**Comment by GuriGuri2013** [comment]
Vale.  Mil gracias por tu tiempo y dedicación.  Mi correo es guriguri2013@outlook.com
