### ISSUE TITLE
Soporte para canales de http://tv.vera.com.uy/

### ISSUE THREAD

**Issue by manolouy** [RosadinTV/rosadintv.github.io#6]
Buenas! Primero que nada gracias por Rosadin. Es el único programa que me funciona sin problemas de buffering para ver iptv.
Quería saber si es posible agregarle soporte para las emisiones de http://tv.vera.com.uy/
Saludos y gracias!

**Comment by RosadinTV** [comment]
Hola, normalmente no doy soporte para este tipo de cosas pero tengo un Plugin que hice hace un tiempo.
Lo descargas y lo mueves a la carpeta Plugins dentro de donde tenes el programa.
https://mega.nz/#!rpoigBia!WN_ZEmTf4wmHSnzTlzwzB1HAlQFziW6kyVmT7orR7OA
PD: Solo funcionan los canales habilitados al publico en la pagina y no me hago responsable si infringe leyes de copyright

**Comment by manolouy** [comment]
Excelente! Muchas gracias!
Existe alguna pagina donde descargar mas plugins de este tipo?

**Comment by RosadinTV** [comment]
Por el momento no tengo muchos mas Plugins interesantes que pueda hacer publicos, quizás en un futuro haga una especie de 'Tienda de Plugins' (obviamente gratis) .. pero por cuestiones de tiempo y copyright veo difícil que eso pase.
Saludos :)
