### ISSUE TITLE
Cambiar grilla de canales

### ISSUE THREAD

**Issue by MsotoM** [RosadinTV/rosadintv.github.io#7]
esto no es un problema, es mas una consulta pero lo dejare aqui (no en pull request)
Es posible crear una grilla de canales en cuadrados y ajustable a la pantalla?? 
como por ejemplo:
http://4.bp.blogspot.com/-GYgCRmqirKQ/Va5IV1bsOZI/AAAAAAAAAXY/Zvze-LKxQQ0/s1600/image007-743290.jpg

es muy complicado??

**Comment by RosadinTV** [comment]
En un futuro es posible que incorpore una opción para poder cambiar la vista.
 No puedo asegurarlo porque seria un tanto complicado de incorporar sin tener que cambiar la base del código del fuente, pero es posible.

**Comment by MsotoM** [comment]
se agradece tu respuesta, una ultima pregunta, existe la forma que tome algunas caracteristicas o atributos que se le colocan en ssiptv, por ejemplo el color del recuadro o tamaño de este??? 
aqui el enlace
http://ss-iptv.com/en/users/51-additional-directives-and-attributes-of-m3u

probe en ssiptv y se ve genial

**Comment by RosadinTV** [comment]
Los estilos que el programa lee actualmente son tvg-logo y [COLOR xxxx]
Ejemplos:
#EXTINF:-1 tvg-logo="http://vignette3.wikia.nocookie.net/dofus/images/1/13/El_Oso_(monstruo).png/revision/20130116195600?path-prefix=es",EJEMPLO ITEM CON LOGO
RTV_NULL
#EXTINF:-1 tvg-logo="http://vignette3.wikia.nocookie.net/dofus/images/1/13/El_Oso_(monstruo).png/revision/20130116195600?path-prefix=es",[COLOR red]EJEMPLO ITEM CON LOGO Y COLOR
RTV_NULL
#EXTINF:-1,[COLOR orange]EJEMPLO ITEM CON COLOR SIN LOGO
RTV_NULL
De todas formas no seria mala idea incorporar esas variantes en un futuro :)

**Comment by RosadinTV** [comment]
Agregue una opción para ver los ítems en forma de cuadricula asi que cierro el reporte.
