### ISSUE TITLE
Existe la posibilidad de crear un tema (Theme)?

### ISSUE THREAD

**Issue by ypolo** [RosadinTV/rosadintv.github.io#9]
Disculpen soy nuevo en esto, tengo conocimientos en CSS y HTML y me parece un estupendo programa un excelente trabajo! y solo mi pregunta es si existe la posibilidad de crear un tema, hacerlo un poco más amigable para la navegación etc, yo podría colaborar en esto pero no se ya luego todo el tema de compilar de nuevo el programa etc. 

Saludos!

**Comment by RosadinTV** [comment]
No es posible crear o cambiar el tema ya que el programa es de código cerrado* y esta programado en VB.NET.
En un futuro es probable que libere el código, pero mientras tanto lo único que es posible cambiar es el color del tema mediante el menú de opciones.
También hay planes para crear un estilo visual nuevo (basado en cuadriculas)
*Los componentes externos y la pagina web si son de código abierto

**Comment by RosadinTV** [comment]
Agregue una opción para ver los ítems en forma de cuadricula así que cierro el reporte.
